services:
  app:
    build: .
    init: true
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
  postgres:
    image: postgres:18
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
          - pgdata:/var/lib/postgresql

volumes:
  pgdata:
